openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
paths:
  /users:
    get:
      tags:
        - user-controller
      summary: Get all users
      description: Return all users from different DBs
      operationId: getUsers
      parameters:
        - name: filters
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Filters'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    Filters:
      type: object
      properties:
        selectFields:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        surname:
          type: string
